name: Issues Event
on: push
jobs:
  createIssue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: creating an issue
        run: |
            gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  issuesEvent:
    needs: createIssue
    runs-on: ubuntu-latest
    steps:
      - name: running issue event
        run: echo "${{ toJSON(github) }}"