name: Issues Event
on: issues
jobs:
#   createIssue:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       issues: write
#     steps:
#       - name: creating an issue
#         run: |
#             gh issue --repo ${{ github.repository }} \
#             create --title "Issue title" --body "Issue body"
#         env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  issuesEvent:
#    needs: createIssue
    runs-on: ubuntu-latest
    steps:
      - name: getting event name
        run: echo "${{ toJSON(github.event_name) }}"
      - name: getting event details
        run: echo "${{ toJSON(github.event) }}"